Project4App/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/homepage'
  get post 'welcome/login'
  get 'projects/viewProjects'
  get 'welcome/logout'
  get 'employees/view_all_emp'

  root 'welcome#homepage'

  resource :employees

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Project4App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Project4App/app/models/employee.rb
class Employee < ApplicationRecord

end

Project4App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Project4App/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index

  end

  def new

  end

  def create
      #render plain: params[:post].inspect
    @username = params[:add_emp][:username]
    @password = params[:add_emp][:password]
    @firstname = params[:add_emp][:firstname]
    @lastname = params[:add_emp][:lastname]
    @sup = params[:add_emp][:supervisor]

    @addemp = ActiveRecord::Base.connection.exec_query %Q{CALL eInsertIntoEmp('#{@username}','#{@password}','#{@firstname}','#{@lastname}','#{@sup}')}
    ActiveRecord::Base.clear_active_connections!

    redirect_to(employees_view_all_emp_url)

  end
  def view_all_emp

    @allEmp = ActiveRecord::Base.connection.exec_query %Q{CALL eGetAllEmp()}
    ActiveRecord::Base.clear_active_connections!

    @allEmpJson = @allEmp.as_json

    @counter = @allEmpJson.length



  end
end

Project4App/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  #called on view projects page load
  def viewProjects
    #setting defualt variables for page
     @empfirstname = session[:firstname]
     @currentProject = 'No Current Project'
     @location = 'No Current Office'
     @firstsups = 'No Current Supervisor'
     @pid = -1
     @eid = session[:eid]

     #Retrieve and parse the current project
     @firstProject = ActiveRecord::Base.connection.exec_query %Q{CALL pGetCurrentProject(#@eid)}
     ActiveRecord::Base.clear_active_connections!

     #convert ActiveRecord object to json
     @jsonObject = @firstProject.as_json

     #if json object is not empty
     if !@jsonObject[0].nil?
       @currentProject = @jsonObject[0]["pname"]
       @location = @jsonObject[0]["location"]
       @pid = @jsonObject[0]["pid"]

      #find supervisors for the first project
      firstProjectSups = ActiveRecord::Base.connection.exec_query %Q{CALL pGetProjectSupervisors(#@pid)}
      ActiveRecord::Base.clear_active_connections!

       #itterate through and parse all the supervisors into one string
       j =0
       @firstsups = String.new
       firstProjectSups = firstProjectSups.as_json
       while j < firstProjectSups.length do
         @firstsups += firstProjectSups[j]["firstname"] +" "+
             firstProjectSups[j]["lastname"] + ", "
         j += 1
       end
     end

     #Get all past/current/future projects for the currently logged in employee
     @results = ActiveRecord::Base.connection.exec_query %Q{CALL pGetEmployeeProjects(#@eid)}
     ActiveRecord::Base.clear_active_connections!

     #conver ActiveRecord object to json
     @employeeProjects = @results.as_json

     #set counter with length of employee projects
     @counter = @employeeProjects.length

    #declare new array for supervisors
     @supers = Array.new

   #iterate through and retrieve al the supervisors for ALL employee projects
     i=0
    while i < @counter
      @tempString = String.new
      @temp = @employeeProjects[i]["pid"]
      @supers[i] = ActiveRecord::Base.connection.exec_query %Q{CALL pGetProjectSupervisors(#@temp)}
      ActiveRecord::Base.clear_active_connections!
      @supers[i] = @supers[i].as_json
      j = 0
      #Parse them as a single string then store them in an array of strings
      while j < @supers[i].length do
         @tempString += @supers[i][j]["firstname"] +" "+ @supers[i][j]["lastname"] + ", "
        j += 1
      end
      @employeeProjects[i]["sups"] = @tempString
      i+=1
    end

  end
end

Project4App/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage

  end
  #declare global variables
  @supervisor = nil

  #runs when the login button is clicked on the login page
  def login

    #retrieve parameters from html field on login page
    @username = params[:login][:username]
    @password = params[:login][:password]




    #search for the existence of @username and @password
    @loginStatus = ActiveRecord::Base.connection.exec_query %Q{CALL pConfirmLogin('#{@username}','#{@password}')}
    ActiveRecord::Base.clear_active_connections!

    #if valid login store session variables
    if !@loginStatus[0].nil?
      session[:eid] = @loginStatus[0]['eid']
      @supervisor = @loginStatus[0]['supervisor']
      session[:supervisor] = @supervisor
      session[:firstname] = @loginStatus[0]["firstname"]
    end



    #find level of account permissions and redirect to the appropriate view
    if @supervisor == 1
      redirect_to(employees_view_all_emp_url)
    elsif @supervisor == 0
      redirect_to(projects_viewProjects_url)
    else
      render plain: 'Invalid Username or Password'
    end
  end

  #runs when logout is clicked in the nav bar
  def logout
    session.clear
    redirect_to(welcome_homepage_url)
  end



end

Project4App/app/helpers/application_helper.rb
module ApplicationHelper
end

Project4App/app/helpers/employees_helper.rb
module EmployeesHelper
end

Project4App/app/helpers/projects_helper.rb
module ProjectsHelper
end

Project4App/app/helpers/sessions_helper.rb
module SessionsHelper
end

Project4App/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Project4App/app/views/employees/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Employee</title>
</head>
<body>
<h3>Add Employee</h3>
<%= form_for :add_emp, url: employees_path do |f| %>
  <p>
      <%=f.label :username %><br>
      <%= f.text_area :username %>
  </p>
    <p>
      <%=f.label :password %><br>
      <%= f.text_area :password %>
    </p>
    <p>
      <%=f.label :firstname %><br>
      <%= f.text_area :firstname %>
    </p>
    <p>
      <%=f.label :lastname %><br>
      <%= f.text_area :lastname %>
    </p>
    <p>
      <%=f.label :supervisor %><br>
      <%= f.text_area :supervisor %>
    </p>
    <p>
        <%= f.submit "Add Employee" %>
    </p>
    <% end %>
</body>
</html>

Project4App/app/views/employees/view_all_emp.html.erb
<nav class="navbar navbar-inverse" style="border-radius:0px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Project 4</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Projects</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="../welcome/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class ="jumbotron">
    <h2>Welcome to All Employees Page </h2>

    <%= link_to '<button type="button">Add New Employee</button>'.html_safe, new_employees_url %>
  </div>
  <h2>Past and Future Projects</h2>
  <table class="table table-bordered table-hover">
    <thead>
    <td>User Name</td>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Supervisor Date</td>
    </thead>
    <tbody>
    <%iterate = 0%>
    <%while iterate < @counter  do %>
        <tr>
          <td>
            <%= @allEmpJson[iterate]["username"]%>
          </td>
          <td>
            <%= @allEmpJson[iterate]["firstname"]%>
          </td>
          <td><%= @allEmpJson[iterate]["lastname"]%></td>
          <td><%= @allEmpJson[iterate]["supervisor"]%></td>
        </tr>
        <%iterate += 1%>
    <%end%>
    </tbody>
  </table>
</div>

Project4App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Project4App/app/views/projects/viewProjects.html.erb
<nav class="navbar navbar-inverse" style="border-radius:0px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Project 4</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Projects</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="../welcome/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <div class ="jumbotron">
    <h2>Welcome <%= @empfirstname %>.<br> </h2>
    <p>You are currently assigned to the <b> <%= @currentProject %></b> project</p>

    <p>
      You are expected to report to your supervisor(s), <%= @firstsups %>
      at the <%= @location %>. For more information click on the project details button
    </p>
    <input type="button" class="btn btn-primary" value="Project Details">
  </div>
  <h2>Past and Future Projects</h2>
  <table class="table table-bordered table-hover">
    <thead>
      <td>Project Name</td>
      <td>Supervisors</td>
      <td>Start Date</td>
      <td>End Date</td>
    </thead>
    <tbody>
    <%iterate = 0%>
    <%while iterate < @counter  do %>
      <tr>
        <td>
              <%= @employeeProjects[iterate]["pname"]%>
        </td>
        <td>
         <%= @employeeProjects[iterate]["sups"]%>
        </td>
        <td><%= @employeeProjects[iterate]["start_date"]%></td>
        <td><%= @employeeProjects[iterate]["end_date"]%></td>
      </tr>
        <%iterate += 1%>
    <%end%>
    </tbody>
  </table>
</div>

Project4App/app/views/welcome/homepage.html.erb
<style>
  .jumbotron{
    background-color: #c7c8b7;
    opacity:0.8;
    width: 100%;
  }
  .btn{

  }
  .card {
    background-color:#c7c8b7;

    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 50px;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
  }
  .card-container.card {
    max-width: 350px;
    padding: 40px 40px;
  }
</style>
<body class="homepage">
<div class="jumbotron"><h2>Project 4 Application</h2></div>

<div class="card card-container" id="loginDiv" hidden="" style="display: block;">
  <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
  <h3>Sign-in</h3>
  <p id="profile-name" class="profile-name-card"></p>

  <%= form_for :login, url: "/welcome/login" do |f| %>

    <span id="reauth-email" class="reauth-email"></span>
    <%=f.text_field :username,class:"form-control",placeholder:"Enter Username",required:"" %>
    <br>
      <%=f.text_field :password,class:"form-control",placeholder:"Enter Password",required:"",type:"password" %>
    <div id="remember" class="checkbox">
     <br>
    </div>

    <%= f.submit "Log in", class:"btn btn-primary"%>
  <% end %>

</div>



</body>

Project4App/app/views/welcome/login.html.erb
<p>Wow you logged in!</p>